#ifndef __ASC_RESULT_CODES_MQH__
#define __ASC_RESULT_CODES_MQH__

enum ASC_ResultCode
  {
   ASC_RC_OK = 0,
   ASC_RC_INVALID_ARGUMENT = 1001,
   ASC_RC_NOT_FOUND = 1002,
   ASC_RC_INVALID_STATE = 1003,
   ASC_RC_IO_FAILED = 2001,
   ASC_RC_BOOTSTRAP_FAILED = 3001,
   ASC_RC_SCAN_FAILED = 4001,
   ASC_RC_DISPATCH_FAILED = 5001,
   ASC_RC_NOT_IMPLEMENTED = 9001
  };

#endif
